code --install-extension adpyke.codesnap
code --install-extension alexcvzz.vscode-sqlite
code --install-extension alvesvaren.arc-dark
code --install-extension austin.code-gnu-global
code --install-extension Battledude.coder200
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension christian-kohler.path-intellisense
code --install-extension ddiu8081.moegi-theme
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ekibun.fortranbreaker
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension fortran-lang.linter-gfortran
code --install-extension Gimly81.fortran
code --install-extension hediet.vscode-drawio
code --install-extension hydralite.hydralite-skyline
code --install-extension jaredkent.laserwave
code --install-extension jithurjacob.nbpreviewer
code --install-extension lehni.vscode-fix-checksums
code --install-extension Levampire.Buttur
code --install-extension mateocerquetella.xcode-12-theme
code --install-extension mgesbert.indent-nested-dictionary
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension mushan.vscode-paste-image
code --install-extension naumovs.color-highlight
code --install-extension negokaz.live-server-preview
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension RobbOwen.synthwave-vscode
code --install-extension s-nlf-fh.glassit
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stackbreak.comment-divider
code --install-extension Tearz.tearz
code --install-extension tinkertrain.theme-panda
code --install-extension travis.simple-dark
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xdebug.php-debug
code --install-extension zhuangtongfa.material-theme
